name: Mirror to Codeberg

on:
  push:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: ssh://git@codeberg.org/<CODEBERG_USER>/<REPO>.git
          REMOTE_NAME: codeberg
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG_SSH_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          PUSH_ALL_REFS: "true"