name: Feature request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to see added?
    validations:
      required: true